name: Android Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Decode Google services configuration file
      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > shoppingList/app/google-services.json

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble